### ISSUE TITLE
Show number of friends or number of groups.

### ISSUE THREAD

**Issue by gham98** [ryanmklee/FacedIn#25]
Need something 'interesting' so counting friends is definitely the easiest. If you want to have fun could also count all friends, groups, and posts in groups to score social engagement but that's work. This sht should be backend.

**Comment by ryanmklee** [comment]
Query for seeing all posts including yours and your friends

```
select user_posts.user_id, name, post, time_posted
from user_posts
join user_data ud on ud.user_id = user_posts.user_id
where user_posts.user_id = '{user_id}'
   or user_posts.user_id in (select friend_id from friend_list_table where friend_list_table.user_id = '{user_id}');
```

[Queries](https://github.com/ryanmklee/FacedIn/blob/master/backend/queries.py)

**Comment by ryanmklee** [comment]
done. documented in backend readme.
